"""Generate src/io/schema_descriptors.cpp from the .proto files in schemas/.

MCAP files with protobuf messages store each message's schema as a serialized
FileDescriptorSet. This embeds those sets in vg_core_io so the library can write
self-describing files without depending on protoc or libprotobuf at runtime.

Needs grpcio-tools (`pip install -e "tools[schemas]"`), which bundles protoc.
"""

from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path

# Message types written to MCAP channels, with the .proto file defining each.
SCHEMAS = {
    "foxglove.CameraCalibration": "foxglove/CameraCalibration.proto",
    "foxglove.CompressedImage": "foxglove/CompressedImage.proto",
    "foxglove.FrameTransforms": "foxglove/FrameTransforms.proto",
    "foxglove.LocationFix": "foxglove/LocationFix.proto",
    "foxglove.PoseInFrame": "foxglove/PoseInFrame.proto",
    "foxglove.RawImage": "foxglove/RawImage.proto",
    "vg.GeoPose": "vg/geo_pose.proto",
    "vg.Imu": "vg/imu.proto",
    "vg.SessionInfo": "vg/session_info.proto",
    "vg.TrackingStatus": "vg/tracking_status.proto",
}

OUTPUT = Path("src/io/schema_descriptors.cpp")


def c_string_literal(data: bytes, width: int = 76) -> str:
    """Return `data` as adjacent C string literals, every byte hex-escaped."""
    escaped = "".join(f"\\x{b:02x}" for b in data)
    step = width - width % 4
    lines = [escaped[i : i + step] for i in range(0, len(escaped), step)] or [""]
    return "\n".join(f'    "{line}"' for line in lines)


def descriptor_set(root: Path, proto: str) -> bytes:
    import grpc_tools
    from grpc_tools import protoc

    well_known = Path(grpc_tools.__file__).parent / "_proto"
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "set.pb"
        args = [
            "protoc",
            f"-I{root / 'schemas'}",
            f"-I{well_known}",
            "--include_imports",
            f"--descriptor_set_out={out}",
            proto,
        ]
        if protoc.main(args) != 0:
            raise SystemExit(f"vg: protoc failed on {proto}")
        return out.read_bytes()


def render(sets: dict[str, bytes]) -> str:
    entries = []
    for i, (name, data) in enumerate(sets.items()):
        entries.append(f"// {name}\nconstexpr char kSchema{i}[] =\n{c_string_literal(data)};")
    table = "\n".join(
        f'    {{"{name}", {{kSchema{i}, sizeof(kSchema{i}) - 1}}}},' for i, name in enumerate(sets)
    )
    return f"""\
// Generated by `vg schemas` from the .proto files in schemas/. Do not edit.

#include "schema_descriptors.hpp"

#include <array>
#include <utility>

namespace vg::io::detail {{
namespace {{

{chr(10).join(entries)}

// clang-format off
constexpr std::array<std::pair<std::string_view, std::string_view>, {len(sets)}> kSchemas{{{{
{table}
}}}};
// clang-format on

}}  // namespace

std::string_view schema_descriptor(std::string_view name) {{
  for (const auto& [schema_name, descriptor] : kSchemas) {{
    if (schema_name == name) {{
      return descriptor;
    }}
  }}
  return {{}};
}}

}}  // namespace vg::io::detail
"""


def generate(root: Path) -> int:
    try:
        import grpc_tools  # noqa: F401
    except ImportError:
        print('vg: grpcio-tools is required: pip install -e "tools[schemas]"', file=sys.stderr)
        return 1
    sets = {name: descriptor_set(root, proto) for name, proto in SCHEMAS.items()}
    out = root / OUTPUT
    out.write_text(render(sets), encoding="utf-8", newline="\n")
    print(f"vg: wrote {OUTPUT}")
    clang_format = subprocess.run(["clang-format", "-i", str(out)], check=False)
    return clang_format.returncode
