function(vg_core_set_warnings target)
  if(MSVC)
    set(_warnings /W4 /permissive-)
    if(VG_CORE_WARNINGS_AS_ERRORS)
      list(APPEND _warnings /WX)
    endif()
  else()
    set(_warnings -Wall -Wextra -Wpedantic -Wshadow -Wconversion -Wsign-conversion)
    if(VG_CORE_WARNINGS_AS_ERRORS)
      list(APPEND _warnings -Werror)
    endif()
  endif()
  target_compile_options(${target} PRIVATE ${_warnings})
endfunction()
